<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Microfauna Guide</title>
    <link rel="stylesheet" href="style.css"> <!-- Reusing your main CSS -->
    <style>
        /* Specific styles for the Microfauna Page */
        .micro-container { padding: 40px; max-width: 1200px; margin: auto; }
        
        .header-nav { display: flex; align-items: center; margin-bottom: 30px; }
        
        .grid-gallery {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 20px;
        }

        .micro-card {
            background: #132938;
            border: 2px solid #1e90ff;
            border-radius: 10px;
            padding: 10px;
            text-align: center;
            cursor: pointer;
            transition: transform 0.2s;
        }

        .micro-card:hover { transform: scale(1.05); }

        .micro-card img {
            width: 100%;
            height: 150px;
            object-fit: cover;
            border-radius: 5px;
        }

        .micro-card h3 { margin-top: 10px; font-size: 1.1rem; color: #a0c4ff; }

        /* Modal Overlay */
        #modalOverlay {
            display: none;
            position: fixed;
            top: 0; left: 0; width: 100%; height: 100%;
            background: rgba(0, 0, 0, 0.9);
            z-index: 10000;
            overflow-y: auto;
        }

        .modal-content {
            background: #0e1a24;
            margin: 5% auto;
            padding: 30px;
            width: 80%;
            max-width: 800px;
            border-radius: 15px;
            border: 2px solid #1e90ff;
            position: relative;
        }

        .back-arrow {
            position: absolute;
            top: 20px; left: 20px;
            font-size: 30px;
            color: #1e90ff;
            cursor: pointer;
            text-decoration: none;
        }

        .modal-body { text-align: center; margin-top: 20px; }
        .modal-main-img { width: 100%; max-height: 400px; object-fit: contain; border-radius: 10px; }
        
        .info-section { text-align: left; margin-top: 20px; }
        .status-good { color: #27ae60; font-weight: bold; }
        .status-bad { color: #e74c3c; font-weight: bold; }

        .more-images-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
            gap: 10px;
            margin-top: 20px;
            display: none; /* Hidden until link clicked */
        }
        .more-images-grid img { width: 100%; border-radius: 5px; }

        .load-more-link {
            color: #1e90ff;
            cursor: pointer;
            text-decoration: underline;
            display: block;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div class="micro-container">
    <div class="header-nav">
        <!-- Back to Index Button -->
        <a href="index.html" class="btn-nav" style="margin-top:0;">← Back to Calculator</a>
        <h1 style="margin-left: 20px;">Microfauna Guide</h1>
    </div>

    <div class="grid-gallery" id="gallery">
        <!-- Cards will be generated by JS -->
    </div>
</div>

<!-- Modal -->
<div id="modalOverlay">
    <div class="modal-content">
        <span class="back-arrow" onclick="closeModal()">←</span>
        
        <div class="modal-body" id="modalBody">
            <!-- Content filled by JS -->
        </div>
    </div>
</div>

<script>
    // 1. Data Object for your Microfauna
    const microData = [
        {
            id: "copepod",
            name: "Copepods",
            status: "Good",
            description: "Tiny, fast-moving crustaceans often seen 'zipping' across the glass or swimming in jerky dashes.",
            role: "They are a natural part of a healthy ecosystem. They eat algae and detritus, and serve as excellent free live food for small fish.",
            removal: "No removal needed! If they are 'taking over,' it usually means you are overfeeding the tank. Siphon the substrate to reduce their numbers.",
            folder: "Copepods"
        },
        {
            id: "limpets",
            name: "Limpets",
            status: "Good",
            description: "Small, snail-like mollusks with a flat, cap-shaped shell. They anchor to one spot and glide very slowly.",
            role: "Excellent algae grazers. They are famous for being one of the few things that efficiently eat 'Green Spot Algae' from plants and glass.",
            removal: "Harmless. If you dislike the look, you can scrape them off manually and siphon them out, or reduce the light to limit their algae food source.",
            folder: "Limpets"
        },
        {
            id: "ostracods",
            name: "Ostracods (Seed Shrimp)",
            status: "Good",
            description: "Tiny 'seeds' with a shell that swim erratically or crawl through the substrate.",
            role: "They are incredible scavengers. They eat uneaten food and fish waste, acting as a secondary clean-up crew for tiny gaps in the gravel.",
            removal: "They are very hard to remove once established, but natural predators like Tetras or Guppies will eat them as a protein-rich snack.",
            folder: "Ostracods"
        },
        {
            id: "hydra",
            name: "Hydra",
            status: "Bad",
            description: "Tiny, stinging polyps that look like miniature green or white umbrellas or trees with long tentacles.",
            role: "They are ambush predators. They use stinging cells to catch small prey. They are dangerous to baby shrimp (fry) and very tiny fish.",
            removal: "Use specialized medications like 'No Planaria' or Panacur. Do NOT crush them; each piece can regenerate into a whole new Hydra.",
            folder: "Hydra"
        },
        {
            id: "planaria",
            name: "Planaria",
            status: "Bad",
            description: "Flatworms with a distinctive triangular (arrow-shaped) head and two visible eyespots. They glide smoothly like slugs.",
            role: "Predatory pests. They produce a paralyzing slime and will hunt baby shrimp, snails, and even eggs. They thrive on excess organic waste.",
            removal: "Use planaria traps with meat bait or treat the tank with 'No Planaria'. Avoid overfeeding to prevent their population from exploding.",
            folder: "Planaria"
        },
        {
            id: "scuds",
            name: "Scuds (Amphipods)",
            status: "Neutral",
            description: "Small, shrimp-like creatures that swim on their sides and run extremely fast across the substrate.",
            role: "Great fish food and clean-up crew. However, in shrimp-only tanks, they can overpopulate and compete for food, or occasionally nip at delicate plants.",
            removal: "Most fish will hunt them to extinction. In shrimp tanks, manual removal via traps or 'nuking' with specific chemicals is sometimes required.",
            folder: "Scuds"
        },
        {
            id: "leeches",
            name: "Leeches",
            status: "Bad",
            description: "Worm-like creatures that move with an inchworm-style 'looping' motion. They are usually thicker and darker than common worms.",
            role: "Predatory or parasitic. Some species specifically target and kill snails or shrimp, draining them of fluids over several hours.",
            removal: "Manual removal with tweezers is best. You can also bait them with a mesh bag of raw liver overnight and remove it before lights come on.",
            folder: "Leeches"
        },
        {
            id: "nematodes",
            name: "Nematodes (Roundworms)",
            status: "Neutral",
            description: "Very thin, hair-like white worms that slither through the substrate or along the glass.",
            role: "Most are harmless detritivores that break down waste. However, 'red' worms hanging from fish (Camallanus) are dangerous parasites.",
            removal: "For harmless detritus types: simply vacuum the gravel and feed less. For red parasitic types: you must use deworming medication like Levamisole.",
            folder: "Nematodes"
        },
        {
            id: "rhabdocoela",
            name: "Rhabdocoela",
            status: "Good",
            description: "Small, harmless flatworms with rounded heads. They are often mistaken for Planaria but lack the arrow-shaped head.",
            role: "They are decomposers that eat poop and leftover food. They are a sign of a healthy, biologically active tank.",
            removal: "No action needed. If they bother you, reduce your feeding frequency and they will naturally die back.",
            folder: "Rhabdocoela"
        },
        {
            id: "protozoa",
            name: "Protozoa / Vorticella",
            status: "Neutral",
            description: "Microscopic organisms. Vorticella looks like 'white fuzz' or 'mold' growing on the shells of shrimp or on plants.",
            role: "Free-swimming protozoa are harmless. However, Vorticella can stress shrimp and interfere with their breathing if it covers their gills.",
            removal: "Improve water quality and increase water changes. Salt dips (1 tbsp/gallon for 60 seconds) can help clear Vorticella off shrimp.",
            folder: "Protozoa"
        },
        {
            id: "daphnia",
            name: "Daphnia (Water Fleas)",
            status: "Good",
            description: "Small, jumping organisms that swim freely in the water column. Usually white or pinkish.",
            role: "Excellent water filters and the 'gold standard' for live fish food. They help clarify green water by eating suspended algae.",
            removal: "Fish will eat them instantly. They are rarely a pest and usually have to be added to a tank on purpose.",
            folder: "Daphnia"
        },
        {
            id: "naidinae",
            name: "Naidinae (Detritus Worms)",
            status: "Good",
            description: "Thin white worms that wriggle vigorously when swimming and slither through the substrate.",
            role: "Foundational part of the ecosystem. They aerate the substrate and break down waste. They are high-protein snacks for fish.",
            removal: "They only appear in large numbers if the tank is 'dirty' or overfed. Siphon your gravel and increase water changes to lower their population.",
            folder: "Naidinae"
        },
        {
            id: "bryozoans",
            name: "Bryozoans",
            status: "Good",
            description: "Colonial organisms that form translucent, brain-like or jelly-like clusters on wood, plants, or glass.",
            role: "Stationary filter feeders. They clean the water by consuming microscopic bacteria. Their presence is a sign of very high water quality.",
            removal: "Completely harmless. If unsightly, they can be gently scraped off, but they are beneficial and fascinating to watch.",
            folder: "Bryozoans"
        }
    ];

    const gallery = document.getElementById('gallery');
    const modal = document.getElementById('modalOverlay');
    const modalBody = document.getElementById('modalBody');

    // 2. Generate Gallery Cards
    microData.forEach(item => {
        const card = document.createElement('div');
        card.className = 'micro-card';
        // Path to image 1 inside the folder
        card.innerHTML = `
            <img src="Microfauna/${item.folder}/1.jpg" alt="${item.name}">
            <h3>${item.name}</h3>
        `;
        card.onclick = () => openModal(item);
        gallery.appendChild(card);
    });

    // 3. Modal Functions
    function openModal(item) {
        const statusClass = item.status.toLowerCase() === 'good' ? 'status-good' : 'status-bad';
        
        modalBody.innerHTML = `
            <img src="Microfauna/${item.folder}/1.jpg" class="modal-main-img">
            <h1>${item.name}</h1>
            <div class="info-section">
                <p><strong>What is it?</strong><br>${item.description}</p>
                <p><strong>Is it good or bad?</strong><br> <span class="${statusClass}">${item.status}</span> - ${item.role}</p>
                <p><strong>How to get rid of it?</strong><br>${item.removal}</p>
            </div>
            
            <span class="load-more-link" onclick="showMoreImages('${item.folder}')">Click here for more images</span>
            <div id="extraImages" class="more-images-grid"></div>
        `;
        modal.style.display = 'block';
        document.body.style.overflow = 'hidden'; // Stop scrolling background
    }

    function closeModal() {
        modal.style.display = 'none';
        document.body.style.overflow = 'auto';
    }

    // 4. Load More Images (2-10)
    function showMoreImages(folder) {
        const grid = document.getElementById('extraImages');
        const link = document.querySelector('.load-more-link');
        grid.innerHTML = ''; // Clear previous
        
        // Loop from 2 to 10
        for(let i = 2; i <= 10; i++) {
            const img = document.createElement('img');
            img.src = `Microfauna/${folder}/${i}.jpg`;
            // Handle missing images gracefully
            img.onerror = function() { this.style.display='none'; }; 
            grid.appendChild(img);
        }
        
        grid.style.display = 'grid';
        link.style.display = 'none'; // Hide the link after clicking
    }

    // Close modal if clicking outside the box
    window.onclick = function(event) {
        if (event.target == modal) {
            closeModal();
        }
    }
</script>

</body>
</html>